Remove some OSL_DEBUG_LEVEL > 1 code
...that would no longer compile since 80fed61a318c4e4d44c4ba2f68a4282fc8ec35d2
"support O(U)String::number() for fast string concatenation", anyway:

> vcl/unx/generic/app/i18n_cb.cxx:508:56: error: incompatible operand types ('const char [14]' and 'OStringNumber<int>')
>                 << ((call_data->type == XIMBitmapType) ?
>                                                        ^

Change-Id: Id7818ed6228ff317e1bee4efd53f15a2786689d4
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/94758
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>