Fix ambiguous calls in C++20
...which added a

> template<class It, class End>
>   constexpr basic_string_view(It begin, End end);

ctor, causing

> vcl/source/window/builder.cxx:2966:35: error: call to 'get' is ambiguous
>                     sFinalValue = Translate::get({sContext.getStr(), sValue.getStr()}, m_pParserState->m_aResLocale);
>                                   ^~~~~~~~~~~~~~
> include/unotools/resmgr.hxx:67:33: note: candidate function
>     UNOTOOLS_DLLPUBLIC OUString get(std::string_view aId, const std::locale &loc);
>                                 ^
> include/unotools/resmgr.hxx:69:33: note: candidate function
>     UNOTOOLS_DLLPUBLIC OUString get(TranslateId sContextAndId, const std::locale &loc);
>                                 ^

etc.

Change-Id: I638be4a3d310179ee73866c4a70b20c49925ede6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/119957
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>