Remove seemingly unused #includes
...that caused

> desktop/source/deployment/gui/dp_gui_extensioncmdqueue.cxx(81,10): error: macro is not used [-Werror,-Wunused-macros]
> # define WIN32_LEAN_AND_MEAN
>          ^

with clang-cl

Change-Id: I129f659aa196e0e713d7bd9065c637d65ee2ac10
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/100118
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>