There doesn't need to be a TemplateSpecializationType here
On both macOS (libc++) and Windows (MSVC standard library),
compilerplugins/clang/test/getstr.cxx failed four tests without this fix:

> error: 'error' diagnostics expected but not seen:
>   File compilerplugins/clang/test/getstr.cxx Line 29: suspicious use of 'getStr' on an object of type 'rtl::OUStringBuffer'; the result is implicitly cast to a void pointer in a call of 'operator <<' [loplugin:getstr]
>   File compilerplugins/clang/test/getstr.cxx Line 30: directly use object of type 'S' (aka 'rtl::OString') in a call of 'operator <<', instead of calling 'getStr' first [loplugin:getstr]
>   File compilerplugins/clang/test/getstr.cxx Line 34: suspicious use of 'getStr' on an object of type 'rtl::OUStringBuffer'; the result is implicitly cast to a void pointer in a call of 'operator <<' [loplugin:getstr]
>   File compilerplugins/clang/test/getstr.cxx Line 35: directly use object of type 'rtl::OString' in a call of 'operator <<', instead of calling 'getStr' first [loplugin:getstr]

Change-Id: I65406d3d84bb5a89df44c8fd665b6e38d19f38c7
Reviewed-on: https://gerrit.libreoffice.org/81266
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>