Drop -I$(dir $(2)) also from gb_*Object__tool_command
...after 8b0c65d0c7873c28cfcc3f304d4a82d4a4346333 "-I$(dir $(3)) in
gb_CObject__command_pattern is no longer needed" and
7fc7993727caa217abc77f60dd1e755cac21749f "-I$(dir $(3)) in
gb_CObject__command_pattern is no longer needed" had already dropped it from
plain gb_CObject__command_pattern.  (f0dea8df211797953aa214234ea2f8f5a67f2971
"support for compiler rewriters" had created gb_*Object__tool_command at a time
when plain gb_*Object__command still contained those -I arguments, so had
presumably just copied them over without a specific additional need to have them
in the tool_command variants; and 8b0c65d0c7873c28cfcc3f304d4a82d4a4346333 and
7fc7993727caa217abc77f60dd1e755cac21749f then just failed to also remove them
from the tool_command variants.)

Presence of the -I arguments in the tool_command variants caused e.g. `make
COMPILER_PLUGIN_TOOL=fakebool` to fail with

> sw/source/filter/ww8/ww8par.cxx:97:10: error: replace <...> include form with "..." for inclusion of a source file next to the current source file, sw/source/filter/ww8/../../core/inc/DocumentRedlineManager.hxx [loplugin:includeform]
> #include <../../core/inc/DocumentRedlineManager.hxx>
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I7ef513507375dcee5d88db53cef58433f7f68e36
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/94867
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>