CLANGTOOLLIBS needs to include -lclangSupport now
...presumably since
<https://github.com/llvm/llvm-project/commit/7a5cb15ea6facd82756adafae76d60f36a0b60fd>
"[RISCV] Lazily add RVV C intrinsics", otherwise causing

> [GEN] compilerplugins/clang/sharedvisitor/analyzer
> /usr/bin/ld: ~/llvm/inst/lib/libclangSema.a(SemaRISCVVectorLookup.cpp.o): in function `clang::CreateRISCVIntrinsicManager(clang::Sema&)':
> ~/github.com/llvm/llvm-project/clang/lib/Sema/SemaRISCVVectorLookup.cpp:195: undefined reference to `clang::RISCV::RVVIntrinsic::computeBuiltinTypes(llvm::ArrayRef<clang::RISCV::PrototypeDescriptor>, bool, bool, bool, unsigned int, bool, clang::RISCV::PolicyScheme, clang::RISCV::Policy)'
[...]

with recent Clang 16 trunk.

It would have been nice to extend the configure check to actually catch that,
but I didn't find any small code sample that would diagnose that:
* Reverting 02faefac39c110f092d585ee7dcd104e375de109 "make the clang plugins
  configure check faster" would cause the configure check to erroneously fail
  due to "no member named 'tooling' in namespace 'clang'".
* And then replacing clang/AST/RecursiveASTVisitor.h with
  clang/Tooling/Tooling.h would make the configure check succeed, and not
  diagnose the above issue.

Change-Id: I6b2eb38daaa1c514fb61652e5bd522f91aa67059
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/137755
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>