call to consteval function is not a constant expression (HAVE_CPP_CONSTEVAL)
...when building with suitable --with-latest-c++ since
b6c13ffe05f6b2e43625ac075f8ff3c01cca3f2e "Simplify static string generation",

> vcl/source/font/font.cxx:396:20: error: call to consteval function 'rtl::OUStringLiteral<96>::OUStringLiteral' is not a constant expression
>             return OUStringLiteral(aArray);
>                    ^
> include/rtl/ustring.hxx:95:16: note: read of non-constexpr variable 'aArray' is not allowed in a constant expression
>         assert(literal[N - 1] == '\0');
>                ^
> vcl/source/font/font.cxx:396:20: note: in call to 'OUStringLiteral(aArray)'
>             return OUStringLiteral(aArray);
>                    ^
> vcl/source/font/font.cxx:393:25: note: declared here
>             sal_Unicode aArray[127 - 32 + 1];
>                         ^

So just keep it easy and spell out the contents explicitly, at least for now.

Change-Id: Ic7d22e7fec3f909e219b428e9b6cf6045a08cb44
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/111734
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>