--enable-python=system no longer works on macOS
e.g.:

> [CXX] pyuno/source/module/pyuno_callable.cxx
> In file included from pyuno/source/module/pyuno_callable.cxx:19:
> In file included from pyuno/source/module/pyuno_impl.hxx:27:
> In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h:85:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/unicodeobject.h:534:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
>     register PyObject *obj,     /* Object */
>     ^~~~~~~~~

(and some $enable_python=system/$_os=Darwin-specific code can thus be removed,
too)

Change-Id: Ic7901732c01bef9335c63dd6f0949453f5824226
Reviewed-on: https://gerrit.libreoffice.org/64732
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>