Fix loplugin:unusedvariablecheck
...on macOS, where it started to cause false positives like

> vcl/inc/osx/a11ywrapper.h:89:98: error: unused parameter 'anAccessibleContext' [loplugin:unusedvariablecheck]
> -(id)initWithAccessibleContext: (css::uno::Reference < css::accessibility::XAccessibleContext >) anAccessibleContext;
>                                                                                                  ^

after 281ebaf2200c32c7bdbbcc93d376d4c813788553 "loplugin:unusedvariablecheck
improve"

Change-Id: I450df3a6d768b4452d0975b5920ea0b3ce53ce13
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/127220
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>