Fix --with-latest-c++ build
...after 33aaafbaf4210f070cf11a4dfc9001164b87e1cf "CppunitTest_sw_uiwriter*:
remove unused includes" and 1167ce36891698551d19d817e56e9250f1742f3a
"CppunitTest_sw_ooxmlexport*: remove unused includes" caused

> In file included from workdir/UnpackedTarball/cppunit/include/cppunit/TestAssert.h:8,
>                  from include/test/bootstrapfixture.hxx:20,
>                  from sw/qa/inc/swmodeltestbase.hxx:26,
>                  from sw/qa/extras/ooxmlexport/ooxmlexport.cxx:10:
> workdir/UnpackedTarball/cppunit/include/cppunit/tools/StringHelper.h: In instantiation of ‘typename std::enable_if<(! std::is_enum<_Tp>::value), std::__cxx11::basic_string<char> >::type CppUnit::StringHelper::toString(const T&) [with T = char16_t; typename std::enable_if<(! std::is_enum<_Tp>::value), std::__cxx11::basic_string<char> >::type = std::__cxx11::basic_string<char>]’:
> workdir/UnpackedTarball/cppunit/include/cppunit/TestAssert.h:74:50:   required from ‘static std::string CppUnit::assertion_traits<T>::toString(const T&) [with T = char16_t; std::string = std::__cxx11::basic_string<char>]’
> workdir/UnpackedTarball/cppunit/include/cppunit/TestAssert.h:168:58:   required from ‘void CppUnit::assertEquals(const T&, const T&, SourceLine, const std::string&) [with T = char16_t; std::string = std::__cxx11::basic_string<char>]’
> sw/qa/extras/ooxmlexport/ooxmlexport.cxx:967:5:   required from here
> workdir/UnpackedTarball/cppunit/include/cppunit/tools/StringHelper.h:25:9: error: use of deleted function ‘std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, char16_t) [with _Traits = char_traits<char>]’
>    25 |     ost << x;
>       |     ~~~~^~~~
> In file included from ~/gcc/trunk/inst/include/c++/12.0.1/bits/unique_ptr.h:41,
>                  from ~/gcc/trunk/inst/include/c++/12.0.1/memory:76,
>                  from sw/qa/inc/swmodeltestbase.hxx:13:
> ~/gcc/trunk/inst/include/c++/12.0.1/ostream:558:5: note: declared here
>   558 |     operator<<(basic_ostream<char, _Traits>&, char16_t) = delete;
>       |     ^~~~~~~~

etc.

Change-Id: I85087a8472eab923065ceb7ca6a1585f7ade75e6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/129118
Reviewed-by: Xisco Fauli <xiscofauli@libreoffice.org>
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>
Tested-by: Jenkins