fix -Werror=extra
error: base class class salhelper::SimpleReferenceObject should be
explicitly initialized in the copy constructor

after
    commit 79c41948dd8899606c0af86705aed42a11628041
    Date:   Fri Jan 18 15:38:07 2019 +0200
    cleanup SwAuthEntry manual ref-counting

Change-Id: I291a8a4f6c2a6ec38506265f6a0382f89774ecd4