Revert "Better use size_t for malloc_size"
This reverts commit 3c28005e3906dbe6c6b5a260323e46d616019920.  Turns out on
Windows read (aka _read) actually has a parameter of type unsigned, not size_t,
(<https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-read?view=msvc-170>
"read"), so this started to cause

> C:/cygwin/home/tdf/jenkins/workspace/lo_tb_master_win64_dbg/soltools/mkdepend/main.c(504): error C2220: the following warning is treated as an error
> C:/cygwin/home/tdf/jenkins/workspace/lo_tb_master_win64_dbg/soltools/mkdepend/main.c(504): warning C4267: 'function': conversion from 'size_t' to 'unsigned int', possible loss of data

(<https://ci.libreoffice.org/job/lo_tb_master_win64_dbg/34368/>) for MSVC builds
targeting x64.

Change-Id: Ica821c8b32e225b7ebbfcbd33d8b7d55515ab3e0
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/135270
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>