desktop: replace boost::bind with lambda or std::bind
This requires working around MSVC 2013 error C3848, that compiler
apparently just doesn't like to call its std::bind() functions if
they're "const".

Change-Id: Ic2e66cab3cadb36ab29cf2504a4c6107334f2ae1