blind fix MSVC werror C4701,C4703 potentially uninitialized local variable
... ´pModelObj´ used. Which is bullshit, but..

Change-Id: Ic731fc92264560c34bd512dc232a9ba901e218a5