Some builds seem to require a prefixed "system" here
... MacOSX-Intel@1-built_no-moz_on_10.6.8 complained with "oleembed.cxx:881:
error: "system" has not been declared"; and see previous
081de50e08d7a5e99ed88da1d3ebd36f4f71efc9 "fwk139: #i10000# adopt for linux."

Change-Id: Ibd6f6aae69a7fcca7a60a85ed2d82dd5e775deea