comphelper::isDebuggerAttached must be defined irrespective of NDEBUG
a57aeff1f3d582c28800d2e4f2c7a9c63d6dbd4e "make isDebuggerAttached() public
comphelper API" had forgotten to drop the NDEBUG condition, causing
--enable-dbgutil --disable-assert-always-abort builds like
<https://ci.libreoffice.org//job/lo_tb_random_config_linux/2215/> to fail with

> /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/workdir/CxxObject/vcl/source/app/watchdog.o: in function `WatchdogThread::start()':
> /lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/vcl/source/app/watchdog.cxx:138: undefined reference to `comphelper::isDebuggerAttached()'
> collect2: error: ld returned 1 exit status
> /lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/vcl/Library_vcl.mk:20: recipe for target '/lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/instdir/program/libvcllo.so' failed

Change-Id: Ia391881f0b6a79709fbebfd204097840a9890147
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/90698
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>