tdf#128710 Qt5 don't force immediate paint on show
I tried to build a minimal reproducer with QMainWindow and a
QDialog and miserably failed. All variants of show, hide, modal
change, move, resize, processEvents(QEventLoop::AllEvents) just
worked. I was able to produce "qt.qpa.xcb: QXcbConnection: XCB
error: 3 (BadWindow) ... major code: 18 (ChangeProperty)" entries
in my ~/.xsession-errors, but that didn't matter for my program.

Then I started to comment code blocks in Qt5Frame and after that
continued in Qt5Widget, found that ShowEvent produced a modal
window, albeit with an obviously missing paint event. But that is
fixable by just queuing one in LO.

I tried to debug that broken behaviour to find the real cause of
the bug, but as I already knew from commit 49cde37d259d ("Qt5
workaround modal change after show bug"), this bug has some timing
related component, so that sadly didn't result in any conclusion.

Change-Id: Iaec45997179365fae5430120f86e435aa5e88447
Reviewed-on: https://gerrit.libreoffice.org/82745
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>
Tested-by: Michael Weghorn <m.weghorn@posteo.de>
Reviewed-by: Jan-Marek Glogowski <glogow@fbihome.de>