Missing include for intptr_t
...at least when building with clang-cl against recent MSVC 2019 standard
library:

> external/clew/source/include\clew/clew.h(319,9): error: unknown type name 'intptr_t'
> typedef intptr_t            cl_context_properties;
>         ^

Change-Id: Ib438b680964028461ac3e566410fc90259d015b2
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/122888
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>