toolkit: export some ListenerMultiplexer types
These are used from svx and apparently some (buggy?) toolchains fail with
fmgridif.cxx:: undefined reference to `non-virtual thunk
 to WindowListenerMultiplexer::acquire()'

Change-Id: Iea0a6eab1ad7f69e4a732f763bc8dbc16bf1be1c