zxing-cpp: upgrade to release 1.4.0
== list of removed patches ==
* 0001-Use-a-patch-file-to-document-changes-from-upstream-s.patch: fixed upstream[1].
* 0002-Update-stb_image_write-from-1.14-to-1.16.patch: fixed upstream.
* 0003-Update-stb_image-from-2.25-to-2.27.patch: fixed upstream
* 0004-Apply-stb-PR-1223-to-stb_image.patch: "stb_image.h" and "stb_image.patch" were removed upstream[1][2].
* include.patch.0: fixed upstream (added #include <cstdint>)[3].
* zxing_newline.patch: this issue has been fixed since gcc 11.2/12 or later[4].

== list of added patches ==
* android_include.patch.0: added missing #include <cmath>(for std::abs)
* assume.__cpp_lib_string_view.patch.0 (by Caolán McNamara): fixed "error: no member named 'asString' in 'ZXing::ByteArray'"

[1] https://github.com/zxing-cpp/zxing-cpp/commit/b208f4bd9052527b7a499d178d81d55b30a27c2d
[2] https://github.com/zxing-cpp/zxing-cpp/commit/d2603139c57e2bbca770656a683abb124adc1591
[3] https://github.com/zxing-cpp/zxing-cpp/commit/53da58625dcd519b7c10e2349a83c9bd10105cf7
[4] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100392

Change-Id: I6266fd6609f0d4235a8d2bcb6571817ef2135101
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/142553
Tested-by: Jenkins
Tested-by: Caolán McNamara <caolanm@redhat.com>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>