fix "Wrap opencl-only functions in appropriate ifdef."
8c64224b4fba5a2d056f220205476b7d2a14250d
(loplugin:unreffun fix) caused:
  'undefined reference to `sc::FormulaGroupInterpreter::msInstance'
when building with --disable-opencl.

(It appears I didn't check whether my build had fully completed before pushing.)

Change-Id: I948205867985c7722662d673e95d5639bc9d9bcc