Try to fix "ERROR: Directory with flag ISINSTALLLOCATION not set!"
This is a regression after my recent changes to Perl code in installer,
most likely commit f6f8437dd0998529234104e0aa6f24b436a96a62, like seen
at https://ci.libreoffice.org/job/lo_daily_tb_win/1213/consoleFull:

> ERROR: Failure in installer.pm
> ERROR: ERROR: Directory with flag ISINSTALLLOCATION not set! at C:/cygwin/home/tdf/jenkins/daily_workspace/tb/src_master/solenv/bin/modules/installer/windows/directory.pm line 334.

I can't repro this problem locally; but as Stephan Bergmann noted,
the mentioned commit changed logic so that a piece of code started
to only execute for CREATE style, where previously it run always.

This tries to re-create the logic prior to the mentioned commit.

Change-Id: I01af06d58b26222bee6220cb9be61cf71940930f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/142152
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>