external/libgpg-error: Missing include (getpid, Windows)
This was apparently missing from 5a0f0139c95dd185da3f80282888e664fada8810
"gpg4libre: update gpgme, libassuan and libgpg-error" but went unnoticed so far
due to the traditionally lax handling of missing function declarations in C, and
only now started to cause

> logging.c(845,57): error: call to undeclared function 'getpid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>                                           (unsigned int)getpid (), pidsuf);
>                                                         ^

with clang-cl 15 trunk after
<https://github.com/llvm/llvm-project/commit/7d644e1215b376ec5e915df9ea2eeb56e2d94626>
"[C11/C2x] Change the behavior of the implicit function declaration warning".

Change-Id: I66dc409f629d9bda807bc9cca21a8a5ecdda79be
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/133338
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>