Fix duplicate "stringresource" in MERGE_LIBRARY_LIST
...where both entries were added with 4f83ec524389997f2237edbc2f7a0d2f7bcdd94c
"add some more libs to libmerged", and defining Library_stringresource in
scripting/Module_scripting.mk is conditional on BUILD_TYPE SCRIPTING.

This will hopefully fix
<https://ci.libreoffice.org/job/lo_callgrind_linux/7884/> (which apparently uses
--enable-mergelibs),

> /usr/bin/ld: /home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/workdir/CxxObject/scripting/source/stringresource/stringresource.o: in function `stringresource::StringResourceImpl::isReadOnly()':
> /home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/scripting/source/stringresource/stringresource.cxx:297: multiple definition of `stringresource::StringResourceImpl::isReadOnly()'; /home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/workdir/CxxObject/scripting/source/stringresource/stringresource.o:/home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/scripting/source/stringresource/stringresource.cxx:297: first defined here
> /usr/bin/ld: /home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/workdir/CxxObject/scripting/source/stringresource/stringresource.o: in function `stringresource::StringResourceImpl::loadLocale(stringresource::LocaleItem*)':
> /home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/scripting/source/stringresource/stringresource.cxx:659: multiple definition of `stringresource::StringResourceImpl::loadLocale(stringresource::LocaleItem*)'; /home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/workdir/CxxObject/scripting/source/stringresource/stringresource.o:/home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/scripting/source/stringresource/stringresource.cxx:659: first defined here
[...]

Change-Id: Ie667487bced048d3b0b0081a9fa4abafa090f02b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/88468
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>
Reviewed-by: Andras Timar <andras.timar@collabora.com>
Tested-by: Jenkins