UBSan needs SwTabFrame RTTI now
...during CppunitTest_sw_uiwriter5,

> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_sw_uiwriter5.so
> workdir/LinkTarget/CppunitTest/libtest_sw_uiwriter5.so: undefined symbol: _ZTI10SwTabFrame"

apparently since 51a558123e323f07ad6bb9985a7c0a5017809f6a "tdf#150976 sw: fix
tracked deletion of row with nested table"

Change-Id: I2a2d5ff53a0e58da9373096ac6a9592410663b5c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/141449
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>