Fix one more get_url_for_data_file
...similar to 4172191ee7d06f142ad93c41c43db7d60f03bdc6 "Fix one more
get_url_for_data_file" etc.

<https://ci.libreoffice.org//job/lo_tb_master_linux_dbg/30817/> had failed
PythonTest_solenv_python with

> Traceback (most recent call last):
>   File "/home/tdf/lode/jenkins/workspace/lo_tb_master_linux_dbg/solenv/qa/python/gbuildtojson.py", line 136, in test_gbuildtojson
>     shutil.copytree(os.path.join(os.environ['SRCDIR'], module), os.path.join(self.tempsrc, module),
>   File "/home/tdf/lode/jenkins/workspace/lo_tb_master_linux_dbg/instdir/program/python-core-3.8.4/lib/shutil.py", line 554, in copytree
>     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
>   File "/home/tdf/lode/jenkins/workspace/lo_tb_master_linux_dbg/instdir/program/python-core-3.8.4/lib/shutil.py", line 510, in _copytree
>     raise Error(errors)
> shutil.Error: [('/home/tdf/lode/jenkins/workspace/lo_tb_master_linux_dbg/sw/qa/uitest/writer_tests/data/.~lock.tdf81457.odt#', '/home/tdf/lode/jenkins/workspace/lo_tb_master_linux_dbg/tempdir/gbuildadynlc3l/sw/qa/uitest/writer_tests/data/.~lock.tdf81457.odt#', "[Errno 2] No such file or directory: '/home/tdf/lode/jenkins/workspace/lo_tb_master_linux_dbg/sw/qa/uitest/writer_tests/data/.~lock.tdf81457.odt#'")]

presumably because UITest_writer_tests was running in parallel and temporarily
created that sw/qa/uitest/writer_tests/data/.~lock.tdf81457.odt# lock file in
the source tree.

Change-Id: Icb735565bbd8b1cdb076d3844efb4a42bc333aa1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/104618
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>