solenv: remove no longer needed OptionalBox widget factory
Not needed since commit f77dc05bde192ebfeaddf8dd5ee8f6013e0196ae
(Resolves: tdf#130513 sfxlo-OptionalBox isn't in sfx, 2020-02-08).

Fixes this Android build error:

/tmp/native-code-7aaa80.o:native-code.cxx:custom_widgets: error: undefined reference to 'makeOptionalBox'

Change-Id: Ib03c9516963e6b14c57ecfca9c7f78132dea2059
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/88514
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>
Tested-by: Caolán McNamara <caolanm@redhat.com>