fix windows 64bit build on vs2015
Visual Studio 2015 will report as follows at the time of 64bit build.

/core/vcl/win/gdi/winlayout.cxx(3972): error C2397:
conversion from 'long' to 'FLOAT' requires a narrowing.

Change-Id: I1a96bd9244c693a3d41b4bf4c2df80ad3b106adc
Reviewed-on: https://gerrit.libreoffice.org/23367
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: jan iversen <jani@documentfoundation.org>