blind fix for breaking windows build
error C2556: 'sal_Bool MNS_InitXPCOM(sal_Bool *)' : overloaded function differs only by return type from 'bool MNS_InitXPCOM(sal_Bool *)'
error C2371: 'MNS_InitXPCOM' : redefinition; different basic types
error C2440: 'initializing' : cannot convert from 'bool *' to 'sal_Bool *'

Change-Id: Ica225dd47e8d90833ce56c0bd4ee38e5013196f6