macOS __arm64__ math.h does not define legacy finite
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/
SDKs/MacOSX.sdk/usr/include/math.h only declares it in an

> #if defined __i386__ || defined __x86_64__
[...]
> /* Legacy BSD API; use the C99 `isfinite( )` macro instead.                   */
> extern int finite(double)
> __API_DEPRECATED("Use `isfinite((double)x)` instead.", macos(10.0, 10.9)) __API_UNAVAILABLE(ios, watchos, tvos);

block, so CppunitTest_odk_checkapi (which deliberately builds in pre-C++11 mode)
failed with

> In file included from ~/lo/core/odk/qa/checkapi/checkapi.cxx:29:
> In file included from ~/lo/core/workdir/CustomTarget/odk/allheaders/allheaders.hxx:351:
> ~/lo/core/include/rtl/math.hxx:352:12: error: use of undeclared identifier 'finite'; did you mean 'isfinite'?
>     return SAL_MATH_FINITE(d);
>            ^

So extend 3e5ec073678ca6c9db862a945eb98b5c243df242 "Try to use isfinite() for
iOS" to all Apple non-Intel platforms.  (We no longer support macOS __i386__
builds, but it probably does not hurt to nevertheless mention it here in the
URE interface sal/mathconf.h include file.)

Change-Id: I9b3a2ec1e48762dd178704185c64d1d3fe358001
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/107714
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>