Fix loplugin:fakebool (clang-cl)
...where it failed with

> In file included from C:/lo-clang/core/extensions/source/activex/SOActiveX.cxx:23:
> C:/lo-clang/core/extensions/source/activex/SOActiveX.h(160,1): error: VarDecl, use "bool" instead of 'BOOL' (aka 'int') [loplugin:fakebool]
> BEGIN_MSG_MAP(CSOActiveX)
> ^~~~~~~~~~~~~~~~~~~~~~~~~
> C:/PROGRA~2/MIB055~1/2019/COMMUN~1/VC/Tools/MSVC/1423~1.281/atlmfc/include\atlwin.h(2692,3): note: expanded from macro 'BEGIN_MSG_MAP'
>                 BOOL bHandled = TRUE; \
>                 ^~~~~~~~~~~~~~~~~~~~

and no idea why I did the getImmediateMacroCallerLoc call in
a822e97d91779fb80f158be6515f2a73488dfba1 "Extend loplugin:salbool to
loplugin:fakebool".  Removing it doesn't cause any issues at least with my local
Linux and Windows --enable-compiler-plugins builds.

Change-Id: I64bd906a34e724aefe980ce8ff2b675e8fb2ec8a
Reviewed-on: https://gerrit.libreoffice.org/83212
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>