fix build with glm 0.9.9
In file included from /usr/include/glm/gtx/norm.hpp:18:0,
                 from /data/rene/git/LibreOffice/master/vcl/inc/opengl/VertexUti
ls.hxx:16,
                 from /data/rene/git/LibreOffice/master/vcl/inc/opengl/LineRende
rUtils.hxx:14,
                 from /data/rene/git/LibreOffice/master/vcl/opengl/LineRenderUti
ls.cxx:11:
/usr/include/glm/gtx/quaternion.hpp:23:3: error: #error "GLM: GLM_GTX_quaternion
 is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
 # error "GLM: GLM_GTX_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
   ^~~~~

so just define it.

Change-Id: I981bfb5fd944f32a3774b3f9b183989773bf235f