ZipPackageHelper is now used in Library_cui outside Library_merged
...since 3eec2a618ea3180040f8f11ed36dc0c18e3727a3 "Added the feature to store
VCL test results as a zip file", see e.g. failed
<https://tinderbox.libreoffice.org/cgi-bin/gunzip.cgi?tree=MASTER&brief-log=1627450201.2981>:

> 61078         /tinderbox/buildslave/build/workdir/CxxObject/cui/source/dialogs/GraphicTestsDialog.o: In function `GraphicsTestsDialog::HandleDownloadRequest(weld::Button&)´:
> 61079         /tinderbox/buildslave/source/libo-master/cui/source/dialogs/GraphicTestsDialog.cxx:87: undefined reference to `utl::ZipPackageHelper::ZipPackageHelper(com::sun::star::uno::Reference<com::sun::star::uno::XComponentContext> const&, rtl::OUString const&)´
> 61080         /tinderbox/buildslave/source/libo-master/cui/source/dialogs/GraphicTestsDialog.cxx:88: undefined reference to `utl::ZipPackageHelper::getRootFolder()´
> 61081         /tinderbox/buildslave/source/libo-master/cui/source/dialogs/GraphicTestsDialog.cxx:88: undefined reference to `utl::ZipPackageHelper::addFolderWithContent(com::sun::star::uno::Reference<com::sun::star::uno::XInterface> const&, rtl::OUString const&)´
> 61082         /tinderbox/buildslave/source/libo-master/cui/source/dialogs/GraphicTestsDialog.cxx:89: undefined reference to `utl::ZipPackageHelper::savePackage()´
> 61083 NEXT    collect2: error: ld returned 1 exit status
> 61084 NEXT    make[1]: *** [/tinderbox/buildslave/source/libo-master/cui/Library_cui.mk:10: /tinderbox/buildslave/build/instdir/program/libcuilo.so] Error 1

Change-Id: Ia7af3bd4ed23adb8cadd66fb20ce8914040eb901
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/119582
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>