fix for windows builds
MSVC does not know and keyword
> InternalDataProvider.cxx(552) : error C2065: ´and´ : undeclared identifier

Change-Id: I7cac0719561b75e37e20534edd2efa5bf3a97fa8
Reviewed-on: https://gerrit.libreoffice.org/30164
Reviewed-by: Jochen Nitschke <j.nitschke+logerrit@ok.de>
Tested-by: Jochen Nitschke <j.nitschke+logerrit@ok.de>