Revert "fdo#62846 incorrect glyph to Unicode mappings in PDFs"
Breaks the build for Windows: vcl/win/source/gdi/winlayout.cxx(1897) :
error C2065: 'nCharPos' : undeclared identifier

This reverts commit 396c2a58122091b6b2956586735890d3893015db.