Revert "tdf#112689: Replace changed O(U)StringBuffer::append() with operator+"
Sorry, but this change breaks the build:
bridges/source/cpp_uno/msvc_win32_x86-64/except.cxx(884): error C2110: '+': cannot add two pointers

This reverts commit 584fb5b42def8da47f2773f756d260b3122e28bc.