Revert "Do not include non-standardized xlocale.h, include locale.h instead"
This reverts commit d264e4e90d0f3639ac752f7e921237637ed36758, which breaks in
external/icu on macOS, <https://ci.libreoffice.org/job/lo_tb_master_mac/20605/>:

> digitlst.cpp:497:8: error: unknown type name 'locale_t'
> static locale_t gCLocale = (locale_t)0;
>        ^