Minimize GtkSalData scope in timeout callback
After commit 63e4c30106bc6a53d42b881e911dcc6baef1b402 this doesn't
anymore generate false positives in the constparams clang plugin:

vcl/unx/gtk/gtkdata.cxx:817:39: error: ...
        ... this parameter can be const [loplugin:constparams]
    static gboolean call_userEventFn( void *data )
                                      ^~~~~~~~~~
1 error generated.

/vcl/unx/gtk3/gtk3gtkdata.cxx:782:39: error: ...
        ... this parameter can be const [loplugin:constparams]
    static gboolean call_userEventFn( void *data )
                                      ^~~~~~~~~~
1 error generated.

Change-Id: Id8d42a0c14bfcc887ec1ecbf70f4c41c26e26efb
Reviewed-on: https://gerrit.libreoffice.org/42912
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Jan-Marek Glogowski <glogow@fbihome.de>