qt: Fix qt6 build after a486cb395ba0bb4b96d1f0039130f27c56aa6c73
Failed like this:

    In file included from /home/michi/development/git/libreoffice/vcl/qt6/QtX11Support.cxx:10:
    /home/michi/development/git/libreoffice/vcl/qt6/../qt5/QtX11Support.cxx:15:10: fatal error: QtX11Extras/QX11Info: No such file or directory
       15 | #include <QtX11Extras/QX11Info>
          |          ^~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[1]: *** [/home/michi/development/git/libreoffice/solenv/gbuild/LinkTarget.mk:334: /home/michi/development/git/libreoffice/workdir/CxxObject/vcl/qt6/QtX11Support.o] Error 1
    make[1]: *** Waiting for unfinished jobs....
    In file included from /home/michi/development/git/libreoffice/vcl/qt6/QtFrame.cxx:10:
    /home/michi/development/git/libreoffice/vcl/qt6/../qt5/QtFrame.cxx: In member function ‘virtual void QtFrame::StartPresentation(bool)’:
    /home/michi/development/git/libreoffice/vcl/qt6/../qt5/QtFrame.cxx:746:5: error: ‘m_ScreenSaverInhibitor’ was not declared in this scope
      746 |     m_ScreenSaverInhibitor.inhibit(bStart, u"presentation", bIsX11, aRootWindow, aDisplay);
          |     ^~~~~~~~~~~~~~~~~~~~~~
    make[1]: *** [/home/michi/development/git/libreoffice/solenv/gbuild/LinkTarget.mk:334: /home/michi/development/git/libreoffice/workdir/CxxObject/vcl/qt6/QtFrame.o] Error 1
    make: *** [Makefile:288: build] Error 2

As mentioned in [1], `QX11Info` has been removed in Qt 6.

The `ScreenSaverInhibitor` related code (except for the `QX11Info` part)
can be used for Qt 6 as well, so adapt the checks in
the header accordingly.

[1] https://www.qt.io/blog/qt-extras-modules-in-qt-6

Co-authored-by: Jan-Marek Glogowski <glogow@fbihome.de>

Change-Id: Ifd546b4f4210aaf7f09ebaa8c36d2a031763d492
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/136091
Reviewed-by: Jan-Marek Glogowski <glogow@fbihome.de>
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>