Blind fix for ENABLE_MERGELIBS
...after e845ff36b245f96ec2d495592f0baa2c0f51048e "tdf#42949 Fix IWYU warnings
in vcl/source/[o-w]*/" had caused tb62 to fail with

> C:/cygwin64/home/buildslave/source/libo-core/vcl/source/window/builder.cxx(1604): error C3861: "SVLIBRARY": Bezeichner wurde nicht gefunden.
[...]
> C:/cygwin64/home/buildslave/source/libo-core/vcl/source/window/builder.cxx(2294): error C3861: "SVLIBRARY": Bezeichner wurde nicht gefunden.

Change-Id: I2102454bf12dc3a04d630ab09cb427471fef99d4
Reviewed-on: https://gerrit.libreoffice.org/78223
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>