error C2513: 'const short' : no variable declared before '='
com/sun/star/beans/PropertyAttribute.hdl's OPTIONAL had a clash with some of
the Windows headers.

Change-Id: I26a4fdcd1a1d53596b82ebdaf609e0a0e9309697