external/lxml: Fix -Wincompatible-function-pointer-types
...with recent Clang 16 trunk since
<https://github.com/llvm/llvm-project/commit/af01f717c48f0fd2481600ed6c00441763365b62>
"Default implicit function pointer conversions diagnostic to be an error",
causing

> src/lxml/etree.c:175589:60: error: incompatible function pointer types passing 'void (void *, void *, xmlChar *)' (aka 'void (void *, void *, unsigned char *)') to parameter of type 'xmlHashScanner' (aka 'void (*)(void *, void *, const unsigned char *)') [-Wincompatible-function-pointer-types]
>   xmlHashScan(__pyx_v_self->__pyx_base._xpathCtxt->nsHash, __pyx_f_4lxml_5etree__registerExsltFunctionsForNamespaces, __pyx_v_self->__pyx_base._xpathCtxt);
>                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> workdir/UnpackedTarball/libxml2/include/libxml/hash.h:213:22: note: passing argument to parameter 'f' here
>                                          xmlHashScanner f,
>                                                         ^

Change-Id: I2a359ed0dfdfa83b49fb03f447967a6d0ff73989
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/138266
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>