fix gcc build error
error: invalid operands of types '__gnu_cxx::__enable_if<true, double>::__type
{aka double}' and 'int' to binary 'operator%'

apparently there's a template returning double for abs for the
non-int/long/float/double argument case. So promote earlier to int so the
abs<int> is called

Change-Id: I882a27c5ec349f894c1c9f4857687360a46b55ae