Revert "Replace list by vector in filtergrouping (sfx2)"
This reverts commit 7f1eaf4044cbd01eade578dc625e75c45998712a.

The usage of iterators in CreateEmptyClassRememberPos
operator() is bogus and causes:

Error: attempt to dereference a singular iterator.