Use DeclCheck at one place in loplugin:implicitboolconversion
...and add tests for those additions to isBoolExpr done in
4786562f56036801d3cfa58c556e537f45ff87b0 "loplugin:implicitboolconversion: warn
about conversions to unsigned char" (and which were added to avoid false
warnings like

> testtools/source/bridgetest/bridgetest.cxx:643:21: error: implicit conversion (IntegralToBoolean) of call argument from 'unsigned char' to 'bool' [loplugin:implicitboolconversion]
>                     (xLBT->transportPolyBoolean(
>                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

and

> cui/source/options/optaboutconfig.cxx:359:62: error: implicit conversion (IntegralToBoolean) of call argument from 'unsigned char' to 'bool' [loplugin:implicitboolconversion]
>                             sValue.append(OUString::boolean( seq[j] ));
>                                                              ^~~~~~

)

Change-Id: I0683144e1c39d31303faf678afaafd708ef7ff79
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/133018
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>