boost: upgrade to release 1.66.0
This claims to support Visual Studio 2017.4, but not the current
2017.5.

* remove boost.auto_link.patch; it does not apply; not sure why we
  need this if we can just define BOOST_ALL_NO_LIB
  (see commit a5871941e0623e8b67adbf700897296738364710)
* remove some hunks from clang-cl.patch.0 that look fixed upstream
* add a global workaround for spurious GCC warning:
  oox/source/drawingml/shape.cxx:921:54: error:
  ‘oShadowColor.boost::optional_detail::tc_optional_base<int>::m_storage’
  may be used uninitialized in this function
  [-Werror=maybe-uninitialized]
                           aFormat.Color = *oShadowColor;

Change-Id: I1eb1d8b66554a84a7d7269f1faaa98695fe2f501
Reviewed-on: https://gerrit.libreoffice.org/48187
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Michael Stahl <mstahl@redhat.com>