Revert "cid#1486241 'Constant' variable guards dead code"
This led to an exception when activating a page via UNO (seen in WollMux):

warn:svtools.uno:211417:211417:svtools/source/uno/wizard/wizardshell.cxx:120: DBG_UNHANDLED_EXCEPTION in enterState exception: com.sun.star.uno.RuntimeException message: [jni_uno bridge error] UNO calling Java method onActivatePage: non-UNO exception occurred: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1
java stack trace:
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1
	at de.muenchen.allg.itd51.wollmux.dialog.mailmerge.MailmergeWizardController.onActivatePage(MailmergeWizardController.java:170)
	at com.sun.star.bridges.jni_uno.JNI_proxy.dispatch_call(Native Method)
	at com.sun.star.bridges.jni_uno.JNI_proxy.invoke(JNI_proxy.java:185)
	at com.sun.proxy.$Proxy118.execute(Unknown Source)
	at de.muenchen.allg.itd51.wollmux.dialog.mailmerge.MailmergeWizardController.startWizard(MailmergeWizardController.java:199)
	at de.muenchen.allg.itd51.wollmux.sidebar.SeriendruckSidebarContent.lambda$new$5(SeriendruckSidebarContent.java:468)

This reverts commit d374d1446b3475977fa2a4dcf36f12e3752b1895.

Change-Id: I6344a83eaa37b58c46a8b576c65bb15b11855c9c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/119655
Tested-by: Jenkins
Reviewed-by: Samuel Mehrbrodt <samuel.mehrbrodt@allotropia.de>