Drop -Wdeclaration-after-statement
It was introduced, without a rationale, into unxgcc.mk in
d30eb8c7532f74377e9c48c2cf23b05d32dc19ba "Warn if declaration follows
statement in C-files", then carried over to clang-cl (com_MSC_defs.mk) with
24fdbe291c827d47e7542de4e6ca44e3598d9054 "clang-cl: Enable more warnings etc.
(like in the Clang/GCC case)", where it now started to cause

> cppuhelper/source/findsofficepath.c(102,20): error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
>     const wchar_t* SUBKEYNAME = L"Software\\LibreOffice\\UNO\\InstallPath";
>                    ^

after
<https://github.com/llvm/llvm-project/commit/118f966b46cfb60897b56a9878e1c68fd0e2afa4>
"[clang][#51931] Enable -Wdeclaration-after-statement for all C versions".

Lets remove it from all toolchain settings, there appears to be not much value
anymore in such a warning about pre-C99 code.

Change-Id: Id4669089e46c97aaa926e5bd202c36eb5984b837
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/130058
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>