Fix linking error of app for iOS in optimized build
ShowLockedDocumentDialog uses the DocumentLockFile API which is not
compiled for non-desktop OSes (see svl/Library_svl.mk). This leads to
an undefined reference to svt::DocumentLockFile::m_bAllowInteraction.
As ShowLockedDocumentDialog isn't used anyway without
HAVE_FEATURE_MULTIUSER_ENVIRONMENT, put it inside such an #if, too.

Thanks to Tsahi Glik <tsahi.glik@cloudon.com> for noticing.

Change-Id: I45d2179395b44709c52ab1871866a2bd5720c8b6