-Werror,-Wunused-but-set-variable (Clang 13 trunk)
7834e431cbc0bc8d2ff99122f01ad348fc296d11 "uitest: add logging for UI actions"
had added the original

>     return "Action on element: " + mxWindow->get_id() + " with action : " + aActionName;

That commit had stated

> The long term goal for this logging is that it generates content in a
> DSL for the UI testing. The generated file can then be interpreted by
> the UI testing and replay the interaction with the UI.
>
> For now the plan is to have a readable output of what happens in the UI
> layer that allows to quickly transform it to a UI test.

Later, 26d464f951a3c28e5a52a3e751a0812c37c993cf "uitest: Some new features in
ui_logger project", apparently as part of working on such a Python-from-DSL code
generator, commented out the original return statement.  The comment at
<https://gerrit.libreoffice.org/c/core/+/116811/
1#message-867650d186ade924cd38240ebbf8603222adac6d> "Lets assume this was
commented out in error" has instructions how to test that (the generated
test.log is in the UserInstallation rather than in instdir, though), and the
comment at <https://gerrit.libreoffice.org/c/core/+/116811/
1#message-36bf2eab1110bf51ccaaa1014188b841beb32041> suggests returning just
aActionName instead of the dressed-up, human-readable "Action on element ..."

However, when I tried out those instructions, the dsl_core.py generation failed
(with an arpeggio.NoMatch exception) both when just returning aActionName and
when returning the full dressed-up, human-readable "Action on element ..."  But
it also generally failed if WindowUIObject::get_action returns an empty string
(i.e., the status quo), with e.g.

> AttributeError: 'CloseDialog' object has no attribute 'uno_command_name'

apparently due to some

> Close Dialog

lines in my generated test.log.

So it appears that dsl_core.py is unfinished work in progress, which does not
work properly regardless of what WindowUIObject::get_action returns.  Coming
back to the original commit that produced "readable output of what happens in
the UI layer", it is thus probably best to leave it at that output for now, and
reinstate the original full dressed-up, human-readable "Action on element ..."
That addresses the -Werror,-Wunused-but-set-variable.  If anybody wants to fix
that dsl_core.py generation, that can happen in later commits.

Change-Id: Ie1123df53d9505fc5f039405f666977550f967d5
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/116811
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>