Updated core Project: help  f4c54d3af32ca4c6d02afff71532dbf10147fd33
Include help2.js not help.js

Otherwise, causes a

  ReferenceError: getParameterByName is not defined

when loading

  <file:///.../instdir/help/index.html?swriter/.uno:HelpIndex?Language=en-US&System=UNIX&Version=6.1>

in the browser.

Change-Id: I13cdd36e44859a74c9a1b4e3b020fed2f56edda0
Reviewed-on: https://gerrit.libreoffice.org/53048
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Olivier Hallot <olivier.hallot@libreoffice.org>