Work around missing InetPtonW
...in certain Windows build environments (whatever it is exactly that causes
some Windows builds to fail with "error C3861: 'InetPtonW': identifier not
found" while others succeed).  Unclear what the original reason was for setting
_WIN32_WINNT here, but removing it hopefully does not break anything.

Change-Id: I83222ad010d428cf2b9c447760ea47381552d04a