GenericSalLayout::KashidaJustify: STL assertion
error: attempt to dereference a singular iterator.
(regression from 03364e13dc10410756057b0b19eaddf82277fb01)