Avoid some unhelpful loplugin:makeshared
...like

> canvas/source/directx/dx_impltools.cxx(137,31): error: rather use make_shared than constructing from 'Gdiplus::Graphics *' [loplugin:makeshared]
>             GraphicsSharedPtr pRet(Gdiplus::Graphics::FromImage(rBitmap.get()));
>                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

on Windows, where those functions like FromImage are provided by Windows (so we
can't help it that they are returning pointers)

Change-Id: Iae5c4b20d64cc6b38ff66409519fbd25f6e509cd
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/100095
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>