use LTO to build hunspell if LTO is enabled
Without this, LTO gcc build may fail while linking libmerged because
of an undefined reference to `std::string::append(char const*)',
which looks like a gcc bug because std::string should be a template,
but whatever, this makes it build.

Change-Id: I173cc0c773d5957a0c4a9cecc74c1ab33afad7db
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/123541
Tested-by: Jenkins
Reviewed-by: Luboš Luňák <l.lunak@collabora.com>