GenericSalLayout::KashidaJustify: STL assertion
error: attempt to compare a dereferenceable iterator to a singular iterator.
(regression from 03364e13dc10410756057b0b19eaddf82277fb01)