Confine findAnnotations to HAVE_FEATURE_PDFIUM
Otherwise e.g. Android builds would fail with

> vcl/source/filter/ipdf/pdfread.cxx:231:77: error: no member named 'PDFiumPage' in namespace 'vcl::pdf'
> std::vector<PDFGraphicAnnotation> findAnnotations(std::unique_ptr<vcl::pdf::PDFiumPage>& pPage,
>                                                                   ~~~~~~~~~~^

etc.

Regression apparently introduced with 86bd98d2d65e16ed9903af37db12d63352772bf2
"extract PDF import for annotations to a separate function".

Change-Id: I364d8d3f30c7eeaa933bfe6aebaf4cad35c20d2b
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/102153
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>