Avoid -Werror=unused-but-set-variable
...in --enable-debug --enable-werror --disable-assert-always-abort builds like
<https://ci.libreoffice.org//job/lo_tb_random_config_linux/2279/>:

> /lo/home/tdf/lode/jenkins/workspace/lo_tb_random_config_linux/xmloff/source/core/xmltoken.cxx:3368:18: error: variable ‘foundDuplicate’ set but not used [-Werror=unused-but-set-variable]
>  3368 |             bool foundDuplicate = false;
>       |                  ^~~~~~~~~~~~~~

Change-Id: If9d433082de84c433132276e171ba5c42c24b61c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/90699
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>