external/gpgmepp: Missing includes (Windows)
> gpgme-w32spawn.c(288,8): error: call to undeclared function 'open'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>   fd = open (trans_file, O_RDONLY);
>        ^

etc. with clang-cl 15 trunk after
<https://github.com/llvm/llvm-project/commit/7d644e1215b376ec5e915df9ea2eeb56e2d94626>
"[C11/C2x] Change the behavior of the implicit function declaration warning",
which went unnoticed so far due to the traditionally lax handling of missing
function declarations in C.

Change-Id: I805ab10d2b0aae3f8b1f46ffeda57aff2bbcef2f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/133340
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>