ScDBDocFunc::Sort: work around STL assertion in sc_unoapi
from dbdocfun.cxx:588:
error: attempt to subscript container with out-of-bounds index 0,
but container only holds 0 elements.

The code in sortparam.cxx still looks quite wrong, and
in table3.cxx there are various arrays hard-coded to size 3...

(regression from 59878d3577246c121bd6345e90adcfca37b499af)