fix build
add #include <optional>, since:
[build CXX] comphelper/source/property/ChainablePropertySetInfo.cxx
/home/rene/LibreOffice/git/master/comphelper/source/property/ChainablePropertySet.cxx: In member function 'virtual void comphelper::ChainablePropertySet::setPropertyValue(const rtl::OUString&, const com::sun::star::uno::Any&)':
/home/rene/LibreOffice/git/master/comphelper/source/property/ChainablePropertySet.cxx:54:10: error: 'optional' is not a member of 'std'
   54 |     std::optional< osl::Guard< comphelper::SolarMutex > > xMutexGuard;
      |          ^~~~~~~~
/home/rene/LibreOffice/git/master/comphelper/source/property/ChainablePropertySet.cxx:23:1: note: 'std::optional' is defined in header '<optional>'; did you forget to '#include <optional>'?
   22 | #include <comphelper/solarmutex.hxx>
  +++ |+#include <optional>
   23 |

happens since 3b2dba2d71e22d8cb7ccc7710588ce645c214afb

Change-Id: I643e7811f1ec7588ccde5453303cd57675c6165e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/135252
Tested-by: Jenkins
Tested-by: René Engelhard <rene@debian.org>
Reviewed-by: René Engelhard <rene@debian.org>