CppunitTest_sw_core_text needs some more RTTI now in UBSan builds
...presumably since 5f6fed508e9942ceb7b4ed6dc02d9c8dbe7c9415 "tdf#144305 sw: fix
rendering of ruby portions with non-default ruby alignment",

> DynamicLibraryManagerException: "Failed to load dynamic library: ~/lo/core/workdir/LinkTarget/CppunitTest/libtest_sw_core_text.so
> ~/lo/core/workdir/LinkTarget/CppunitTest/libtest_sw_core_text.so: undefined symbol: _ZTI13SwLinePortion"

and

> DynamicLibraryManagerException: "Failed to load dynamic library: ~/lo/core/workdir/LinkTarget/CppunitTest/libtest_sw_core_text.so
> ~/lo/core/workdir/LinkTarget/CppunitTest/libtest_sw_core_text.so: undefined symbol: _ZTI14SwMultiPortion"

Change-Id: Iaebffc3c9c0245d6092ef1dfc58213fd2d38d303
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/122143
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>