Revert "use intrinsict to inline InterlockCount() on Windows too"
This reverts commit 06fd022e722946398c7b938a63c738d8f32ffcfa.

The commit breaks smoketest on Windows, for reasons unknown:
C:/cygwin/home/tinderbox/tinderbox-master-build-libreoffice/smoketest/smoketest.cxx(197) : error : Assertion
Test name: `anonymous namespace'::Test::test
assertion failed
- Expression: connection_.isStillAlive()

I can't see why the commit should matter, given that the functions
should be equivalent according to my reading of the docs. And debugging
this on Windows is pain squared, so I can't even figure out what is
going wrong where. Feel free to try your luck.

Note that when debugging this, the code triggering this seems to be
run only if SOLAR_JAVA and JAVA_HOME are set, so 'make verbose=t'
and running just the command without this hides the problem.