We need to call decode method considering this:
java.lang.NumberFormatException: For input string: "#FF9966"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:481)
	at java.lang.Integer.parseInt(Integer.java:527)
	at com.sun.star.wizards.form.StyleApplier.getStyleColor(StyleApplier.java:321)

When creating form with wizard

Partly reverts http://cgit.freedesktop.org/libreoffice/core/commit/?id=94404e40f257b40bed186edba9b2035aadcae8e7

Change-Id: Ide85566244e0dce1d30f6369d1f5d8d30534a01a