Flatpak: Upgrade to 21.08 runtime, disable Skia
For whatever reason, building Skia against the 21.08 SDK would fail with

> /run/build/libreoffice/workdir/UnpackedTarball/skia/src/ports/SkFontHost_FreeType_common.cpp: In function ‘void {anonymous}::colrv1_draw_paint(SkCanvas*, const FT_Color*, FT_Face, FT_COLR_Paint)’:
> /run/build/libreoffice/workdir/UnpackedTarball/skia/src/ports/SkFontHost_FreeType_common.cpp:668:14: error: ‘FT_COLR_PAINTFORMAT_TRANSFORMED’ was not declared in this scope; did you mean ‘FT_COLR_PAINTFORMAT_TRANSFORM’?
>   668 |         case FT_COLR_PAINTFORMAT_TRANSFORMED: {
>       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |              FT_COLR_PAINTFORMAT_TRANSFORM
> /run/build/libreoffice/workdir/UnpackedTarball/skia/src/ports/SkFontHost_FreeType_common.cpp:669:60: error: ‘union FT_COLR_Paint_::<unnamed>’ has no member named ‘transformed’; did you mean ‘transform’?
>   669 |             SkMatrix transform = ToSkMatrix(colrv1_paint.u.transformed.affine);
>       |                                                            ^~~~~~~~~~~
>       |                                                            transform
> /run/build/libreoffice/workdir/UnpackedTarball/skia/src/ports/SkFontHost_FreeType_common.cpp: In function ‘bool {anonymous}::colrv1_traverse_paint(SkCanvas*, const FT_Color*, FT_Face, FT_OpaquePaint)’:
> /run/build/libreoffice/workdir/UnpackedTarball/skia/src/ports/SkFontHost_FreeType_common.cpp:763:14: error: ‘FT_COLR_PAINTFORMAT_TRANSFORMED’ was not declared in this scope; did you mean ‘FT_COLR_PAINTFORMAT_TRANSFORM’?
>   763 |         case FT_COLR_PAINTFORMAT_TRANSFORMED:
>       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |              FT_COLR_PAINTFORMAT_TRANSFORM
> /run/build/libreoffice/workdir/UnpackedTarball/skia/src/ports/SkFontHost_FreeType_common.cpp:768:74: error: ‘union FT_COLR_Paint_::<unnamed>’ has no member named ‘transformed’; did you mean ‘transform’?
>   768 |                     colrv1_traverse_paint(canvas, palette, face, paint.u.transformed.paint);
>       |                                                                          ^~~~~~~~~~~
>       |                                                                          transform
> make[1]: *** [/run/build/libreoffice/solenv/gbuild/LinkTarget.mk:347: /run/build/libreoffice/workdir/GenCxxObject/UnpackedTarball/skia/src/ports/SkFontHost_FreeType_common.o] Error 1

But including Skia in the Linux flatpak isn't too useful anyway (and just
happened to be on by default):  First, it is disabled by default on Linux, cf.
UseSkia in officecfg/registry/data/org/openoffice/Office/Common.xcu.  And
second, on Linux it can only be enabled for SAL_USE_VCLPLUGIN=gen, but not for
the gtk3 plugin that the flatpak normally uses, cf.
OfaViewTabPage::UpdateSkiaStatus in cui/source/options/optgdlg.cxx.

Change-Id: Ifdc9c23676280caf19db0e9f09df15aaa21eef5f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/121705
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>