fix 32bit build in new a11y cppunit tests
/<<PKGBUILDDIR>>/toolkit/qa/cppunit/a11y/XAccessibleComponentTester.cxx: In member function ‘void XAccessibleComponentTester::testBounds()’:
/<<PKGBUILDDIR>>/toolkit/qa/cppunit/a11y/XAccessibleComponentTester.cxx:51:5: error: no matching function for call to ‘assertGreaterEqual(int, sal_Int32&, CppUnit::SourceLine, const char [1])’
   51 |     CPPUNIT_ASSERT_GREATEREQUAL(0, bounds.X);
      |     ^
/usr/include/cppunit/TestAssert.h:251:6: note: candidate: ‘template<class T> void CppUnit::assertGreaterEqual(const T&, const T&, CppUnit::SourceLine, const string&)’
  251 | void assertGreaterEqual( const T& expected,
      |      ^~~~~~~~~~~~~~~~~~
/usr/include/cppunit/TestAssert.h:251:6: note:   template argument deduction/substitution failed:
/<<PKGBUILDDIR>>/toolkit/qa/cppunit/a11y/XAccessibleComponentTester.cxx:51:5: note:   deduced conflicting types for parameter ‘const T’ (‘int’ and ‘sal_Int32’ {aka ‘long int’})
   51 |     CPPUNIT_ASSERT_GREATEREQUAL(0, bounds.X);
      |     ^

etc.

Regression from 6c719f01c2980954deec588142c89d9ebb4ecbfc

Change-Id: I123894e5ed6d6f3bcf46b1c5b37f1f49cb5f9f99
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/135630
Tested-by: Jenkins
Tested-by: René Engelhard <rene@debian.org>
Reviewed-by: René Engelhard <rene@debian.org>