Missing include
Building on Windows with PCH disabled:

[CXX] vcl/jsdialog/jsdialogbuilder.cxx
C:\lo\src\core\include\rtl/ref.hxx(113): error C2027: use of undefined type 'TabPage'
C:\lo\src\core\include\vcl/tabctrl.hxx(33): note: see declaration of 'TabPage'
C:\lo\src\core\include\rtl/ref.hxx(111): note: while compiling class template member function 'rtl::Reference<reference_type>::~Reference(void)'
with
[
reference_type=TabPage
]
C:/lo/src/core/vcl/jsdialog/jsdialogbuilder.cxx(207): note: see reference to function template instantiation 'rtl::Reference<reference_type>::~Reference(void)'
being compiled
with
[
reference_type=TabPage
]
C:\lo\src\core\include\vcl/vclptr.hxx(64): note: see reference to class template instantiation 'rtl::Reference<reference_type>' being compiled
with
[
reference_type=TabPage
]
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\utility(289): note: see reference to class template instantiation 'VclPtr<TabPage>' being co
mpiled
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\utility(290): note: see reference to class template instantiation 'std::pair<VclPtr<TabPage>
,VclPtr<VclGrid>>' being compiled
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\xtree(330): note: see reference to class template instantiation 'std::pair<const rtl::OStrin
g,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>' being compiled
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\xtree(752): note: see reference to class template instantiation 'std::_Tree_node<std::pair<c
onst rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>,std::_Default_allocator_traits<_Alloc>::void_pointer>' being compiled
with
[
_Alloc=std::allocator<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>
]
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\xtree(1189): note: see reference to function template instantiation 'void std::_Tree_val<std
::_Tree_simple_types<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>>::_Erase_head<std::allocator<std::_Tree_node<std::pair<const rtl:
:OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>,std::_Default_allocator_traits<_Alloc>::void_pointer>>>(_Alnode &) noexcept' being compiled
with
[
_Alloc=std::allocator<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>,
_Alnode=std::allocator<std::_Tree_node<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>,std::_Default_allocator_traits<std::allocator<st
d::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>>::void_pointer>>
]
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\xtree(1189): note: see reference to function template instantiation 'void std::_Tree_val<std
::_Tree_simple_types<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>>::_Erase_head<std::allocator<std::_Tree_node<std::pair<const rtl:
:OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>,std::_Default_allocator_traits<_Alloc>::void_pointer>>>(_Alnode &) noexcept' being compiled
with
[
_Alloc=std::allocator<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>,
_Alnode=std::allocator<std::_Tree_node<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>,std::_Default_allocator_traits<std::allocator<st
d::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>>::void_pointer>>
]
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\xtree(1187): note: while compiling class template member function 'std::_Tree<std::_Tmap_tra
its<_Kty,_Ty,_Pr,_Alloc,false>>::~_Tree(void) noexcept'
with
[
_Kty=rtl::OString,
_Ty=std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>,
_Pr=std::less<rtl::OString>,
_Alloc=std::allocator<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>
]
C:\lo\src\core\vcl\inc\jsdialog/jsdialogbuilder.hxx(131): note: see reference to function template instantiation 'std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_All
oc,false>>::~_Tree(void) noexcept' being compiled
with
[
_Kty=rtl::OString,
_Ty=std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>,
_Pr=std::less<rtl::OString>,
_Alloc=std::allocator<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>
]
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\Include\map(75): note: see reference to class template instantiation 'std::_Tree<std::_Tmap_traits<_
Kty,_Ty,_Pr,_Alloc,false>>' being compiled
with
[
_Kty=rtl::OString,
_Ty=std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>,
_Pr=std::less<rtl::OString>,
_Alloc=std::allocator<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>
]
C:\lo\src\core\vcl\inc\salvtables.hxx(1032): note: see reference to class template instantiation 'std::map<rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid
>>,std::less<rtl::OString>,std::allocator<std::pair<const rtl::OString,std::pair<VclPtr<TabPage>,VclPtr<VclGrid>>>>>' being compiled
make[1]: *** [C:/lo/src/core/solenv/gbuild/LinkTarget.mk:303: C:/lo/src/build/workdir/CxxObject/vcl/jsdialog/jsdialogbuilder.o] Error 2

Change-Id: Id67ce45b1652a2915508963adb65e1e1f5c51dcd
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/94464
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>