Create destination directory also for non-empty sourcepath directory
Do not attempt to copy anything. This can happen with
instdir/share/extensions being populated from some build (e.g. by
dictionaries) but no extension to be installed.

The result was
ERROR: Can't copy file: /build/core/instdir/share/extensions -> /build/usr/opt/core/lib/libreoffice/share/extensions
Is a directory at /build/core/solenv/bin/modules/installer/worker.pm line 350.

and the copy() created the destination as 0-length file instead.

The recent changes not copying extensions/packages.txt anymore and
related may have triggered this:

4a59b5bbb993978bc8bbcdbab19c43f6eaf9c65e Fix and simplify "any bundled extensions installed" check
d6dcb3d456a6614ecb80abaa140948b73bd808bb gb_Package_Package must specify a directory
1a8f1f0ec7b6c23e5d38798bf20dd114586edff1 Remove unused $(LIBO_SHARE_FOLDER)/extensions/package.txt

Change-Id: I93c1b0867bf234255fdef9d31c447b9b20011e17
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/120164
Reviewed-by: Eike Rathke <erack@redhat.com>
Tested-by: Jenkins