Blind fix for sporadically failing UITests
Attempting to avoid this problem:

  ======================================================================
  ERROR: test_tracked_changes_acceptall (trackedChanges.CalcTrackedChanges)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "C:/lo/src/core/sc/qa/uitest/calc_tests4/trackedChanges.py", line 127, in test_tracked_changes_acceptall
      gridwin = xCalcDoc.getChild("grid_window")
  uno.com.sun.star.uno.RuntimeException: Could not find child with id: grid_window

  ======================================================================
  ERROR: test_tracked_changes_reject (trackedChanges.CalcTrackedChanges)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "C:/lo/src/core/sc/qa/uitest/calc_tests4/trackedChanges.py", line 173, in test_tracked_changes_reject
      gridwin = xCalcDoc.getChild("grid_window")
  uno.com.sun.star.uno.RuntimeException: Could not find child with id: grid_window

  ======================================================================
  ERROR: test_tracked_changes_rejectall (trackedChanges.CalcTrackedChanges)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "C:/lo/src/core/sc/qa/uitest/calc_tests4/trackedChanges.py", line 239, in test_tracked_changes_rejectall
      gridwin = xCalcDoc.getChild("grid_window")
  uno.com.sun.star.uno.RuntimeException: Could not find child with id: grid_window

The problem looks unexpected, since UITest.create_doc_in_start_center
waits for "OnNew" event, but who knows...

Change-Id: I38207944f0f2fb67cf6e97ee1c220bbd95dc7047
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/116698
Tested-by: Jenkins
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>