sw: fix crash in InitBookmarks() with forum-mso-en-8410.docx
Error: attempt to dereference a past-the-end iterator.

Probably this only crashes in the assert(iter->pNode...) as the rest of
the function already checks that "iter == end".

(regression from commit 3d4c99942923984793b1a1df6d32fd8295e673b5)

Change-Id: If652a15d1cdebb21fbce028fceeaee8dce8f7f6d
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/138205
Tested-by: Jenkins
Reviewed-by: Caolán McNamara <caolanm@redhat.com>