Revert "silence gcc4.8 warning"
This reverts commit 7d03f80528431e76e1a867b54a9180da3f3d85f5.

GCC does not like the pragma:
error: ‘-Werror’ is not an option that controls warnings [-Werror=pragmas]

Change-Id: I8b97f39056091df644bcfe570332738560cd5dc3