Missing test dependency
> include/c++/10.0.0/bits/unique_ptr.h:81: error: undefined reference to 'SvxNumberInfoItem::~SvxNumberInfoItem()'
> collect2: error: ld returned 1 exit status
> make[1]: *** [solenv/gbuild/LinkTarget.mk:639: workdir/LinkTarget/CppunitTest/libtest_sc_screenshots.so] Error 1

Change-Id: Ifb498e7a54b37bd93c71110b6d7cfda4ea8ef1b5
Reviewed-on: https://gerrit.libreoffice.org/81805
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>