Fix 'make translations' run
Recent commits introduced strings in .ui files without context
which makes 'make translations' fail with:

[build POT] pot.done
Traceback (most recent call last):
  File "/home/gabor/src/core/solenv/bin/uiex", line 30, in <module>
    keyid = entry.msgctxt + '|' + entry.msgid
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Affected commits are:
66b0bd66a0fa997ed8d63ec21638ff2d4549133d
c2d9d1d447845b0c58ae132097ad96ae7f7a8cf5

Change-Id: If7afc4bb157a6406cabba141d375e9b0dab5f3de
Reviewed-on: https://gerrit.libreoffice.org/41322
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Katarina Behrens <Katarina.Behrens@cib.de>