Fix Clang 10 -Werror,-Wimplicit-int-float-conversion
> idlc/source/astexpression.cxx:330:68: error: implicit conversion from 'sal_Int32' (aka 'int') to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-int-float-conversion]
>                     if (ev->u.fval < SAL_MIN_INT32 || ev->u.fval > SAL_MAX_INT32)
>                                                                  ~ ^~~~~~~~~~~~~
> include/sal/types.h:209:32: note: expanded from macro 'SAL_MAX_INT32'
> #define SAL_MAX_INT32         ((sal_Int32)  0x7FFFFFFF)
>                                ^~~~~~~~~~~~~~~~~~~~~~~
> idlc/source/astexpression.cxx:414:58: error: implicit conversion from 'sal_uInt32' (aka 'unsigned int') to 'float' changes value from 4294967295 to 4294967296 [-Werror,-Wimplicit-int-float-conversion]
>                     if (ev->u.fval < 0.0 || ev->u.fval > SAL_MAX_UINT32)
>                                                        ~ ^~~~~~~~~~~~~~
> include/sal/types.h:210:32: note: expanded from macro 'SAL_MAX_UINT32'
> #define SAL_MAX_UINT32        ((sal_uInt32) 0xFFFFFFFF)
>                                ^~~~~~~~~~~~~~~~~~~~~~~
> idlc/source/astexpression.cxx:492:68: error: implicit conversion from 'sal_Int64' (aka 'long') to 'float' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-int-float-conversion]
>                     if (ev->u.fval < SAL_MIN_INT64 || ev->u.fval > SAL_MAX_INT64)
>                                                                  ~ ^~~~~~~~~~~~~
> include/sal/types.h:212:32: note: expanded from macro 'SAL_MAX_INT64'
> #define SAL_MAX_INT64         ((sal_Int64)  SAL_CONST_INT64(0x7FFFFFFFFFFFFFFF))
>                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> idlc/source/astexpression.cxx:501:68: error: implicit conversion from 'sal_Int64' (aka 'long') to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-int-float-conversion]
>                     if (ev->u.dval < SAL_MIN_INT64 || ev->u.dval > SAL_MAX_INT64)
>                                                                  ~ ^~~~~~~~~~~~~
> include/sal/types.h:212:32: note: expanded from macro 'SAL_MAX_INT64'
> #define SAL_MAX_INT64         ((sal_Int64)  SAL_CONST_INT64(0x7FFFFFFFFFFFFFFF))
>                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> idlc/source/astexpression.cxx:574:58: error: implicit conversion from 'sal_uInt64' (aka 'unsigned long') to 'float' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-int-float-conversion]
>                     if (ev->u.fval < 0.0 || ev->u.fval > SAL_MAX_UINT64)
>                                                        ~ ^~~~~~~~~~~~~~
> include/sal/types.h:213:32: note: expanded from macro 'SAL_MAX_UINT64'
> #define SAL_MAX_UINT64        ((sal_uInt64) SAL_CONST_UINT64(0xFFFFFFFFFFFFFFFF))
>                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> idlc/source/astexpression.cxx:583:58: error: implicit conversion from 'sal_uInt64' (aka 'unsigned long') to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-int-float-conversion]
>                     if (ev->u.dval < 0.0 || ev->u.dval > SAL_MAX_UINT64)
>                                                        ~ ^~~~~~~~~~~~~~
> include/sal/types.h:213:32: note: expanded from macro 'SAL_MAX_UINT64'
> #define SAL_MAX_UINT64        ((sal_uInt64) SAL_CONST_UINT64(0xFFFFFFFFFFFFFFFF))
>                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Consitently use the new o3tl::convertsToAtLeast/Most(o3tl::roundAway(...), ...)
for all cases in coerce_value that check that a floating-point value falls into
an integer range, even those that don't cause a warning.

The new idlc/test/parser/conversion.tests is deliberately left out of
unoidl/CustomTarget_unoidl-write_test.mk. as unoidl-write doesn't support such
conversions from floating-point to integer types.

Change-Id: Ie00923e665f2bcb306e1e328614c75b9247512ee
Reviewed-on: https://gerrit.libreoffice.org/77353
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>