external/skia: Missing include
> In file included from workdir/UnpackedTarball/skia/third_party/vulkanmemoryallocator/GrVulkanMemoryAllocator.cpp:27:
> In file included from workdir/UnpackedTarball/skia/third_party/vulkanmemoryallocator/GrVulkanMemoryAllocator.h:35:
> workdir/UnpackedTarball/skia/third_party/vulkanmemoryallocator/include/vk_mem_alloc.h:2817:9: error: use of undeclared identifier 'snprintf'
>         snprintf(outStr, strLen, "%u", static_cast<unsigned int>(num));
>         ^

etc.

Change-Id: I4f13c8a137f23ef62d67c3b4dfa8f1c0ddfc5ec9
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/145552
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>