Revert "Some lower objects coupling."
This reverts commit 37d83008261432819afb57e5bcf761c913a71ebd.

Reason for revert: Does not compile
/home/tdf/lode/jenkins/workspace/lo_ubsan/nlpsolver/ThirdParty/EvolutionarySolver/src/net/adaptivebox/deps/DEPSAgent.java:45: error: DEPSAgent is not abstract and does not override abstract method setLibrary(Library) in ILibEngine
public class DEPSAgent implements ILibEngine {
       ^
1 error

Change-Id: I72f2a22ab1f4119178f8002c21ba0845c4cd1bdf
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/119040
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>