Fix bogus OUString constructor fixes.
0b571f9d2fcb7bf99daf9bebf49082540cff711b
(remove redundant calls to OUString constructor)
introduced:
error: variable 'sComposedName' is uninitialized when used within its own initialization

Change-Id: I846337da43625d1cdbd33f0705499daa0c419894