Add missing semicolon
...in code recently introduced in b60fd4019f26475439fb689b1761cd48c482a54b
"related tdf#151548 sw: KEY_DOWN access to FieldmarkWithDropDownButton", which
at least GCC 12 and recent GCC 13 trunk in an --enable-dbgutil
--enable-optimized --enable-werror build diagnosed as

> sw/source/core/crsr/bookmark.cxx: In member function ‘void sw::mark::FieldmarkWithDropDownButton::LaunchPopup()’:
> sw/source/core/crsr/bookmark.cxx:669:30: error: ‘this’ pointer is null [-Werror=nonnull]
>   669 |         m_pButton->Invalidate();
>       |         ~~~~~~~~~~~~~~~~~~~~~^~
> cc1plus: all warnings being treated as errors

Change-Id: I1e6d7e7e0244259674d41edff4c07a2de2b74bdc
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/141791
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>