tdf#153533 Fix chart2_import test failure on HiDPI display
The test checks that the text shape width is smaller than the chart
wall. This test fails on HiDPI displays. For example:

--------------------
lode/dev/core/chart2/qa/extras/chart2import.cxx(2207) : error : Assertion
Test name: Chart2ImportTest::testFixedSizeBarChartVeryLongLabel
double equality assertion failed
- Expected: 4800
- Actual  : 4632
- Delta   : 100

Failures !!!
Run: 85   Failure total: 1   Failures: 1   Errors: 0
--------------------

Now, instead of testing the
exact value of the text shape width, I have used CPPUNIT_ASSERT_LESS()
to make sure that the above condition holds:

 CPPUNIT_ASSERT_LESS(xChartWall->getSize().Width, xXAxis->getSize().Width)

This is done in two different tests:

* Chart2ImportTest::testFixedSizeBarChartVeryLongLabel()
* Chart2ImportTest::testAutomaticSizeBarChartVeryLongLabel()

Both tests are among those that can be invoked with:

  cd chart2 && make CppunitTest_chart2_import

Change-Id: Ifb28fcf91da451aecdadff7a95aa810ef16fc510
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/146815
Tested-by: Jenkins
Reviewed-by: Hossein <hossein@libreoffice.org>