Adapt loplugin:implicitboolconversion to _G_STR_NONNULL
...from glib2-devel-2.76.0-1.fc38.x86_64, causing

> libreofficekit/source/gtk/lokdocview.cxx:390:28: error: implicit conversion (IntegralCast) from 'bool' to 'int' [loplugin:implicitboolconversion]
>     pLOEvent->m_pCommand = g_strdup(pCommand);
>                            ^~~~~~~~~~~~~~~~~~
> /usr/include/glib-2.0/glib/gstrfuncs.h:212:35: note: expanded from macro 'g_strdup'
>         const char *const __str = _G_STR_NONNULL (___str);                    \
>                                   ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/glib-2.0/glib/gstrfuncs.h:157:34: note: expanded from macro '_G_STR_NONNULL'
> #define _G_STR_NONNULL(x) ((x) + !(x))
>                                  ^~~~

Change-Id: Iec20b20992a61fd48155f338a10dc313411448f8
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/148948
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>