-Werror,-Wuninitialized (apparently new in Clang 12 trunk)
> cppuhelper/source/typemanager.cxx:1571:47: error: field 'entity_' is uninitialized when used here [-Werror,-Wuninitialized]
>         ServiceBasedSingletonDescription_Base(entity_->isPublished()),
>                                               ^

The code was like that ever since it was introduced in
71f921206b6dadcd404a5edb78f796567971dc66 "WIP: Experimental new binary type.rdb
format".  Odd that that never caused an issue, but the code appears to at least
never be executed during `make check`.

Change-Id: I19fe78162c7c4a9211c380648595df9aa54bf4d7
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/100554
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>