Missing include (Windows --disable-pch)
> sw/source/core/doc/docfld.cxx(558,18): error: member access into incomplete type 'const ::utl::TransliterationWrapper'
>         if( rSCmp.isEqual( rDBName, sName.getToken(0, ';') ) )
>                  ^

Change-Id: I041879acb350a2bc42133f55be5a1501ffe93c95
Reviewed-on: https://gerrit.libreoffice.org/82272
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>