canvas: error C2397: conversion from 'size_t' to 'BYTE' requires ...
a narrowing conversion (at least other people's MSVC says so, mine
doesn't complain)

Change-Id: Ic87da76567778884b81361067075fd9325e2d276