Revert "There's no reason for these defaults in one constructor but not the other"
The reason is that dbaccess_unoapi dbaccess.ORowSet fails with:

lib.StatusException: couldn't set up test environment
    at mod._dbaccess.ORowSet.createTestEnvironment(ORowSet.java:479)

This reverts commit c8e6626724cea46280ec5d23824e2b5efabad506.