Fix !HAVE_FEATURE_MULTIUSER_ENVIRONMENT build
The Android-ARM_24-Bytemark-Hosting build currentl< fails with:
error: unused parameter ´pLockData´ [-Werror,-Wunused-parameter]

Regression from commit 03b3d369bb8f ("Show who has locked the
document when reopening a read-only document").

Change-Id: I6d8f900957d79a9c5bf70645e2021995e8a28d43
Reviewed-on: https://gerrit.libreoffice.org/75145
Tested-by: Jenkins
Reviewed-by: Jan-Marek Glogowski <glogow@fbihome.de>