Avoid loplugin:salcall
> In file included from jurt/source/pipe/staticsalhack.cxx:39:
> sal/osl/unx/module.cxx:212:6: error: SAL_CALL unnecessary here [loplugin:salcall]
> void SAL_CALL osl_unloadModule(oslModule hModule)
> ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

in an ASan+UBSan build with --enable-compiler-plugins, after
4116fe5d0608881375480a43ba09d324ad8fdf0f "Add HAVE_(UNIX_)DLAPI config header
define".  DISABLE_DYNLOADING was defined there ever since
16e3c221ef3191a412f1a5a570d4809a1818a875 "Poor hack for libjpipe.so under Clang
-fsanitize=*" but doesn't appear to be necessary.  (Alternatively,
loplugin:salcall could be taught not to warn if the function definition involves
any #if'ery.)

Change-Id: I5786979eb944d59f969c9875d77b03f9b2432161
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/128797
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>