Only build LOKDocView-0.1.gir when necessary
Prior to 4b00b24bf9be9a867b5ad5331a0cec47fcf30142 "sysui: fix rpm errors in
freedesktop-menus (4.14.1)" it had been build as part of
sysui/desktop/share/create_tree.sh, which is presumably only called when
building for deb or rpm PKGFORMAT.  Building it now in more cases started to
cause issues, like

> g-ir-scanner: link: /home/sbergman/llvm/inst/bin/clang --gcc-toolchain=/home/sbergman/gcc/trunk/inst -fdiagnostics-color -fsanitize=address -fsanitize-address-globals-dead-stripping -fsanitize-address-use-after-scope -fsanitize=undefined -fsanitize=local-bounds -fsanitize=nullability -o /home/sbergman/lo/core/tmp-introspectga_nlzjv/LOKDocView-0.1 /home/sbergman/lo/core/tmp-introspectga_nlzjv/LOKDocView-0.1.o -L. -Wl,-rpath,. -Wl,--no-as-needed -L/home/sbergman/lo/core/instdir/program -Wl,-rpath,/home/sbergman/lo/core/instdir/program -llibreofficekitgtk -lgio-2.0 -lgobject-2.0 -Wl,--export-dynamic -pthread -lgmodule-2.0 -lglib-2.0
> /usr/bin/ld: /home/sbergman/lo/core/instdir/program/liblibreofficekitgtk.so: undefined reference to `__ubsan_handle_function_type_mismatch_v1'
> /usr/bin/ld: /home/sbergman/lo/core/instdir/program/liblibreofficekitgtk.so: undefined reference to `__ubsan_vptr_type_cache'
> /usr/bin/ld: /home/sbergman/lo/core/instdir/program/liblibreofficekitgtk.so: undefined reference to `__ubsan_handle_dynamic_type_cache_miss'

in an ASan+UBSan build (where g-ir-scanner should apparently use CXX instead of
CC for linking, but there appears to be no easy way to tell g-ir-scanner to do
so).

Change-Id: I5a960c6ed387722138d4b3d156c87038f3e5b8ca
Reviewed-on: https://gerrit.libreoffice.org/76769
Tested-by: Jenkins
Reviewed-by: Noel Grandin <noel.grandin@collabora.co.uk>