-wd4505 is still needed
...see e.g. <https://ci.libreoffice.org//job/lo_tb_master_win/29066>

> C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win/unotools/source/config/bootstrap.cxx(269): error C2220: the following warning is treated as an error
> C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win/unotools/source/config/bootstrap.cxx(269): warning C4505: 'utl::dbgCheckStatusOfURL': unreferenced local function has been removed

where the OSL_ASSERT used in

> OSL_ASSERT(aStatus != Bootstrap::PATH_VALID || dbgCheckStatusOfURL(sDerivedURL) == Bootstrap::PATH_VALID);

is defined in terms of SAL_DETAIL_WARN_IF_FORMAT, which in turn is careful to
make its contents visible to the compiler even under --disable-sal-log.  That
MSVC warning, about a function whose only reference is in code that the compiler
can statically determine to be unreachable, is really unhelpful.

This partially reverts 93fff6bb50b6e8cadb88f93a811fd268731abd89 "remove some
MSVC -wd".

Change-Id: Ie337989ee0ca6b7d7f29a50026fa249b0b266474
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/107716
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>