Fix build on big-endian platforms with clang
Reportedly, this builds OK with gcc, but not with clang (rightfully).

/tmp/usr/ports/editors/libreoffice/work/libreoffice-6.3.0.4/connectivity/source/drivers/odbc/OTools.cxx:148:21:
error: arithmetic on a pointer to void
_pValue += _nSize - properSize;
~~~~~~~ ^
1 error generated.

The pointer arithmetics on void* was introduced in 2012 in commit
45c6551a7afd1480e3dfc9c495915ed62e2b30cb.

Change-Id: I78beddeda8bc516e45dd2a99dba8c7b8b1cf9255
Reviewed-on: https://gerrit.libreoffice.org/78076
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>
Tested-by: Mike Kaganski <mike.kaganski@collabora.com>