Missing include
> include\rtl/ref.hxx(129): error C2027: use of undefined type 'SvXMLImportPropertyMapper'
> include\xmloff/shapeimport.hxx(46): note: see declaration of 'SvXMLImportPropertyMapper'
> include\rtl/ref.hxx(127): note: while compiling class template member function 'rtl::Reference<SvXMLImportPropertyMapper>::~Reference(void)'
> include\xmloff/xmlprcon.hxx(64): note: see reference to function template instantiation 'rtl::Reference<SvXMLImportPropertyMapper>::~Reference(void)' being compiled
> include\xmloff/xmlprcon.hxx(37): note: see reference to class template instantiation 'rtl::Reference<SvXMLImportPropertyMapper>' being compiled

Change-Id: I77083e021ae16bce8b2f749b96b6c6607c22ff87
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/146072
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>