Silence some clang-cl loplugin:stringstatic
For one, do not warn about global declarations in included files, as generally
not all uses of the variable are seen to decided whether it would be good to
replace.  That covers cases like

> In file included from dtrans/source/win32/dtobj/DataFmtTransl.cxx:26:
> dtrans/source/win32/dtobj/MimeAttrib.hxx(29,16): error: rather declare this using OUStringLiteral/OStringLiteral/char[] [loplugin:stringstatic]
> const OUString CHARSET_UTF16        ("utf-16");
> ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For another, do not warn about variables whose pData member is used. That covers
cases like

> sal/osl/w32/procimpl.cxx(347,20): error: rather declare this using OUStringLiteral/OStringLiteral/char[] [loplugin:stringstatic]
>     const OUString ENV_COMSPEC ("COMSPEC");
>     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I75c1048098b63164bdb583695951f73964cb24f8
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/101134
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>