-Werror,-Wunused-but-set-variable (Clang 13 trunk)
> sd/source/ui/dlg/BulletAndPositionDlg.cxx:707:14: error: variable 'sSelectStyle' set but not used [-Werror,-Wunused-but-set-variable]
>     OUString sSelectStyle;
>              ^

...ever since the code's introduction in
38448c24b0cec3f74a3c727ac7adddb23c5b0e6f "Add new customize and position merged
dialog", and which means that SvxBulletAndPositionDlg::m_sBulletCharFormatName
and second parameter of SvxBulletAndPositionDlg::SetCharFmts, both also
introduced in that commit, were equally unused

Change-Id: Id07c05777817298073d85719689b391bda533221
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/116821
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>