Avoid LIBO_USE_SOURCE_LOCATION feature on user-facing LockFileException
(see f6b69b43d1a8f5b5cf4e4f80c6cc5e8542bfb8ea "use
std::experimental::source_location in uno::Exception"), causing the unopkg
executable to print something like

> ERROR: unopkg cannot be started. The lock file indicates it is already running. If this does not apply, delete the lock file at:
> ~/.config/libreoffice/4/.lock desktop/source/pkgchk/unopkg/unopkg_shared.h:44

mentioning an unhelpful source location

Change-Id: Ie9ed716c9edc6c73c173a034ce8bd9bfaf05c0c9
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/120669
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>