Revert "vcl: two printing headers should be private Unix headers"
This reverts commit 8060c41dfacf9c618bf7a480c5aabee5d82f0ff2.
It breaks several TBs
eg:
/Users/cloph/source/libo-core/sw/source/uibase/dbui/dbmgr.cxx:140:10: fatal error: 'config_cups.h' file not found
         ^