external/freetype: Avoid duplicate zlib symbols
After 46b09d95b60e5ef1f176e280706bcaed99b22215 "Update freetype to 2.12.0", my
--without-system-freetype --without-system-zlib Linux build started to fail to
link Library_skia with

> ld.lld: error: duplicate symbol: zlibVersion
> >>> defined at zutil.c:28 (workdir/UnpackedTarball/zlib/zutil.c:28)
> >>>            zutil.o:(zlibVersion) in archive core/workdir/LinkTarget/StaticLibrary/libzlib.a
> >>> defined at zutil.c:28 (src/gzip/zutil.c:28)
> >>>            ftgzip.o:(.text+0x0) in archive workdir/UnpackedTarball/freetype/instdir/lib/libfreetype.a

etc. because both those non-system libraries are provided as static archives.

There is also provisioning for symbol renaming in
workdir/UnpackedTarball/freetype/src/gzip/ftzconf.h via -DZ_PREFIX, so enable
that.  But three symbols were missing and would still produce linker failures,
so add them with external/freetype/zlib-duplicates.patch.

Change-Id: Ibe876d4e38e3e44ce00c64fb70c88fb0b1e3a910
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/142788
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>